//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TownUtilityBillSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int ID { get; set; }
        public string NUMBER { get; set; }
        public int CUSTOMER_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public string PERIOD { get; set; }
        public decimal SUM { get; set; }
        public bool PAID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
